//! Generate honest, committable TRUST.md from the active identity.

use std::path::Path;

use crate::config::Config;
use crate::identity::IdentityRecord;
use crate::trust_tier::{resolve_primary_tier, TierHints};

#[cfg_attr(not(test), allow(dead_code))]
pub fn render_trust_md(config: &Config, identity: &IdentityRecord) -> String {
    render_trust_md_with_hints(config, identity, TierHints {
        has_active_identity: true,
        has_sha256sums: false,
        has_sums_signature: false,
    })
}

/// Like [`render_trust_md`], but uses filesystem hints for inferred tier.
pub fn render_trust_md_at(
    config: &Config,
    identity: &IdentityRecord,
    project_root: &Path,
) -> String {
    render_trust_md_with_hints(config, identity, TierHints::probe(project_root))
}

fn render_trust_md_with_hints(
    config: &Config,
    identity: &IdentityRecord,
    hints: TierHints,
) -> String {
    let app = &config.project.name;
    let meta = &identity.meta;
    let fp = &meta.fingerprint_sha256;
    let tier = resolve_primary_tier(config, hints);
    let tier_id = tier.as_str();
    let tier_meaning = tier.meaning();

    let mut platforms = Vec::new();
    if config.platforms.windows {
        platforms.push("Windows");
    }
    if config.platforms.macos {
        platforms.push("macOS");
    }
    if config.platforms.linux {
        platforms.push("Linux");
    }
    let platforms = if platforms.is_empty() {
        "Windows, macOS, Linux".to_string()
    } else {
        platforms.join(", ")
    };

    let notes_block = if config.trust.notes.is_empty() {
        String::new()
    } else {
        let mut s = String::from("\n### Maintainer notes\n\n");
        for note in &config.trust.notes {
            s.push_str("- ");
            s.push_str(note);
            s.push('\n');
        }
        s
    };

    format!(
        r#"# Trust kit — {app}

This file is generated by `signet trust`. It is safe to commit.

Self-signed releases are **not** the same as paid Apple / Microsoft / Google developer
program signatures. Operating systems may still show warnings (SmartScreen, Gatekeeper, etc.).
That is expected for independent and non-profit OSS using self-signing.

## Publisher identity

| Field | Value |
|-------|-------|
| App | `{app}` |
| Identity name | `{name}` |
| Common name (CN) | `{cn}` |
| Organization | `{org}` |
| SHA-256 fingerprint | `{fp}` |
| Valid from | `{not_before}` |
| Valid until | `{not_after}` |
| Key algorithm | `{algo}` |

Compare the fingerprint above with the one printed by:

```bash
signet identity show
```

Never trust a build whose fingerprint does not match.

## Trust tier

| Field | Value |
|-------|-------|
| Primary tier | `{tier_id}` |

{tier_meaning}

This integrity tier **does not imply** OS or store reputation (SmartScreen, Gatekeeper,
Play App Signing, or Apple notarization). See [docs/trust-model.md](docs/trust-model.md)
in the Signet project for the full tier table.
{notes_block}
## Verify a downloaded artifact

1. Download the installer / bundle and the published checksums (when available).
2. Confirm the release is from this project's known repository or channel.
3. After install (or on the binary), confirm the signing certificate fingerprint matches `{fp}` when platform tooling allows.
4. If the OS warns that the publisher is unknown, that can still be a legitimate self-signed build — use the fingerprint, not the absence of a warning, as your check.

(When available, prefer `signet verify` to check fingerprints and SHA256SUMS in one step.)

## Platform notes ({platforms})

Do **not** install this publisher certificate into Trusted Root (or equivalent) on end-user
PCs. That is unsafe advice and Signet will never recommend it. Developer machines and
enterprise MDM are different contexts — still never tell public users to trust your root.

### Windows

- SmartScreen may warn until the certificate builds reputation (or you use a paid Authenticode cert).
- Self-signing does **not** silence SmartScreen by itself.
- Advanced users can inspect the signature properties on the `.exe` / `.msi` and compare the certificate thumbprint / fingerprint to the table above.

### macOS

- Gatekeeper may block or warn on apps that are not notarized through Apple.
- Notarization requires an Apple Developer account and is **out of scope** for free self-signing.
- Users may need to explicitly allow the app in System Settings after verifying the publisher fingerprint.

### Linux

- Distributions vary; checksum verification is the primary trust check for many AppImage/deb/rpm flows.
- When packages are signed, verify with the project's published fingerprint / key as documented for that format.

## What signet will never put here

- Private keys
- Passwords or PFX passphrases
- CI secrets
- Instructions for end users to install certificates into Trusted Root

Private material stays under the project's gitignored `.signet/` directory.
"#,
        name = meta.name,
        cn = meta.common_name,
        org = if meta.organization.is_empty() {
            "—"
        } else {
            meta.organization.as_str()
        },
        fp = fp,
        not_before = meta.not_before,
        not_after = meta.not_after,
        algo = meta.key_algorithm,
        tier_id = tier_id,
        tier_meaning = tier_meaning,
        notes_block = notes_block,
        platforms = platforms,
        app = app,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, Trust};
    use crate::identity::{create_identity, CreateOptions};
    use tempfile::tempdir;

    fn sample_identity(dir: &Path) -> IdentityRecord {
        create_identity(
            dir,
            &CreateOptions {
                name: "default".into(),
                common_name: "Trust Demo".into(),
                organization: "Org".into(),
                days: 30,
                force: false,
            },
        )
        .unwrap()
    }

    #[test]
    fn trust_contains_fingerprint_not_key() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains(&rec.meta.fingerprint_sha256));
        assert!(!md.contains(&rec.key_pem));
        assert!(!md.contains("BEGIN PRIVATE KEY"));
        assert!(md.contains("SmartScreen"));
        assert!(md.contains("Gatekeeper"));
    }

    #[test]
    fn trust_contains_tier_and_root_anti_pattern() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains("self_signed_host"));
        assert!(md.contains("## Trust tier"));
        assert!(md.contains("Trusted Root"));
        assert!(md.contains("does not imply"));
        assert!(md.contains("signet verify"));
    }

    #[test]
    fn declared_tier_and_notes_appear() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let mut cfg = Config::example("trust-demo", ".");
        cfg.trust = Trust {
            declared_tier: Some("checksum_only".into()),
            notes: vec!["Beta channel only".into()],
        };
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains("checksum_only"));
        assert!(md.contains("Beta channel only"));
        assert!(md.contains("### Maintainer notes"));
    }
}
