//! Generate honest, committable TRUST.md from the active identity.

use crate::config::Config;
use crate::identity::IdentityRecord;

pub fn render_trust_md(config: &Config, identity: &IdentityRecord) -> String {
    let app = &config.project.name;
    let meta = &identity.meta;
    let fp = &meta.fingerprint_sha256;

    let mut platforms = Vec::new();
    if config.platforms.windows {
        platforms.push("Windows");
    }
    if config.platforms.macos {
        platforms.push("macOS");
    }
    if config.platforms.linux {
        platforms.push("Linux");
    }
    let platforms = if platforms.is_empty() {
        "Windows, macOS, Linux".to_string()
    } else {
        platforms.join(", ")
    };

    format!(
        r#"# Trust kit — {app}

This file is generated by `signet trust`. It is safe to commit.

Self-signed releases are **not** the same as paid Apple / Microsoft / Google developer
program signatures. Operating systems may still show warnings (SmartScreen, Gatekeeper, etc.).
That is expected for independent and non-profit OSS using self-signing.

## Publisher identity

| Field | Value |
|-------|-------|
| App | `{app}` |
| Identity name | `{name}` |
| Common name (CN) | `{cn}` |
| Organization | `{org}` |
| SHA-256 fingerprint | `{fp}` |
| Valid from | `{not_before}` |
| Valid until | `{not_after}` |
| Key algorithm | `{algo}` |

Compare the fingerprint above with the one printed by:

```bash
signet identity show
```

Never trust a build whose fingerprint does not match.

## Verify a downloaded artifact

1. Download the installer / bundle and the published checksums (when available).
2. Confirm the release is from this project's known repository or channel.
3. After install (or on the binary), confirm the signing certificate fingerprint matches `{fp}` when platform tooling allows.
4. If the OS warns that the publisher is unknown, that can still be a legitimate self-signed build — use the fingerprint, not the absence of a warning, as your check.

## Platform notes ({platforms})

### Windows

- SmartScreen may warn until the certificate builds reputation (or you use a paid Authenticode cert).
- Self-signing does **not** silence SmartScreen by itself.
- Advanced users can inspect the signature properties on the `.exe` / `.msi` and compare the certificate thumbprint / fingerprint to the table above.

### macOS

- Gatekeeper may block or warn on apps that are not notarized through Apple.
- Notarization requires an Apple Developer account and is **out of scope** for free self-signing.
- Users may need to explicitly allow the app in System Settings after verifying the publisher fingerprint.

### Linux

- Distributions vary; checksum verification is the primary trust check for many AppImage/deb/rpm flows.
- When packages are signed, verify with the project's published fingerprint / key as documented for that format.

## What signet will never put here

- Private keys
- Passwords or PFX passphrases
- CI secrets

Private material stays under the project's gitignored `.signet/` directory.
"#,
        name = meta.name,
        cn = meta.common_name,
        org = if meta.organization.is_empty() {
            "—"
        } else {
            meta.organization.as_str()
        },
        fp = fp,
        not_before = meta.not_before,
        not_after = meta.not_after,
        algo = meta.key_algorithm,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use crate::identity::{create_identity, CreateOptions};
    use tempfile::tempdir;

    #[test]
    fn trust_contains_fingerprint_not_key() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = create_identity(
            &root,
            &CreateOptions {
                name: "default".into(),
                common_name: "Trust Demo".into(),
                organization: "Org".into(),
                days: 30,
                force: false,
            },
        )
        .unwrap();
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains(&rec.meta.fingerprint_sha256));
        assert!(!md.contains(&rec.key_pem));
        assert!(!md.contains("BEGIN PRIVATE KEY"));
        assert!(md.contains("SmartScreen"));
        assert!(md.contains("Gatekeeper"));
    }
}
