//! Generate honest, committable TRUST.md from the active identity.

use std::fs;
use std::path::Path;

use crate::config::Config;
use crate::identity::IdentityRecord;
use crate::sign::SumsKeyPaths;
use crate::trust_tier::{resolve_primary_tier, TierHints};

#[cfg_attr(not(test), allow(dead_code))]
pub fn render_trust_md(config: &Config, identity: &IdentityRecord) -> String {
    render_trust_md_with_hints(
        config,
        identity,
        TierHints {
            has_active_identity: true,
            has_sha256sums: false,
            has_sums_signature: false,
        },
        None,
    )
}

/// Like [`render_trust_md`], but uses filesystem hints for inferred tier.
pub fn render_trust_md_at(
    config: &Config,
    identity: &IdentityRecord,
    project_root: &Path,
) -> String {
    render_trust_md_with_hints(
        config,
        identity,
        TierHints::probe(project_root),
        Some(project_root),
    )
}

fn render_trust_md_with_hints(
    config: &Config,
    identity: &IdentityRecord,
    hints: TierHints,
    project_root: Option<&Path>,
) -> String {
    let app = &config.project.name;
    let meta = &identity.meta;
    let fp = &meta.fingerprint_sha256;
    let tier = resolve_primary_tier(config, hints);
    let tier_id = tier.as_str();
    let tier_meaning = tier.meaning();

    let mut platforms = Vec::new();
    if config.platforms.windows {
        platforms.push("Windows");
    }
    if config.platforms.macos {
        platforms.push("macOS");
    }
    if config.platforms.linux {
        platforms.push("Linux");
    }
    let platforms = if platforms.is_empty() {
        "Windows, macOS, Linux".to_string()
    } else {
        platforms.join(", ")
    };

    let notes_block = if config.trust.notes.is_empty() {
        String::new()
    } else {
        let mut s = String::from("\n### Maintainer notes\n\n");
        for note in &config.trust.notes {
            s.push_str("- ");
            s.push_str(note);
            s.push('\n');
        }
        s
    };

    let minisign_pub = project_root.and_then(|root| {
        let paths = SumsKeyPaths::from_secrets_dir(&config.secrets_path(root));
        fs::read_to_string(&paths.public).ok()
    });
    let minisign_block = minisign_trust_section(minisign_pub.as_deref());
    let android_block = android_trust_section(project_root.map(|r| config.secrets_path(r)).as_deref());
    let ios_block = ios_trust_section(project_root, config);
    let graduation_block = graduation_trust_section(config);

    format!(
        r#"# Trust kit — {app}

This file is generated by `signet trust`. It is safe to commit.

Self-signed releases are **not** the same as paid Apple / Microsoft / Google developer
program signatures. Operating systems may still show warnings (SmartScreen, Gatekeeper, etc.).
That is expected for independent and non-profit OSS using self-signing.

## Publisher identity

| Field | Value |
|-------|-------|
| App | `{app}` |
| Identity name | `{name}` |
| Common name (CN) | `{cn}` |
| Organization | `{org}` |
| SHA-256 fingerprint | `{fp}` |
| Valid from | `{not_before}` |
| Valid until | `{not_after}` |
| Key algorithm | `{algo}` |

Compare the fingerprint above with the one printed by:

```bash
signet identity show
```

Never trust a build whose fingerprint does not match.

## Trust tier

| Field | Value |
|-------|-------|
| Primary tier | `{tier_id}` |

{tier_meaning}

This integrity tier **does not imply** OS or store reputation (SmartScreen, Gatekeeper,
Play App Signing, or Apple notarization). See [docs/trust-model.md](docs/trust-model.md)
in the Signet project for the full tier table.
{notes_block}{minisign_block}{android_block}{ios_block}{graduation_block}
## Verify a downloaded artifact

1. Download the installer / bundle and the published checksums (when available).
2. Confirm the release is from this project's known repository or channel.
3. After install (or on the binary), confirm the signing certificate fingerprint matches `{fp}` when platform tooling allows.
4. If the OS warns that the publisher is unknown, that can still be a legitimate self-signed build — use the fingerprint, not the absence of a warning, as your check.
5. Prefer `signet verify` (and `signet verify --require-sig` when `SHA256SUMS.minisig` is published).

## Platform notes ({platforms})

Do **not** install this publisher certificate into Trusted Root (or equivalent) on end-user
PCs. That is unsafe advice and Signet will never recommend it. Developer machines and
enterprise MDM are different contexts — still never tell public users to trust your root.

### Windows

- SmartScreen may warn until the certificate builds reputation (or you use a paid Authenticode cert).
- Self-signing does **not** silence SmartScreen by itself.
- Advanced users can inspect the signature properties on the `.exe` / `.msi` and compare the certificate thumbprint / fingerprint to the table above.

### macOS

- Gatekeeper may block or warn on apps that are not notarized through Apple.
- Notarization requires an Apple Developer account and is **out of scope** for free self-signing.
- Users may need to explicitly allow the app in System Settings after verifying the publisher fingerprint.

### Linux

- Distributions vary; checksum verification is the primary trust check for many AppImage/deb/rpm flows.
- When packages are signed, verify with the project's published fingerprint / key as documented for that format.
- Prefer `signet verify --require-sig` or `minisign -Vm SHA256SUMS -p minisign.pub` when a minisign public key is published above.

## What signet will never put here

- Private keys
- Passwords or PFX passphrases
- CI secrets
- Instructions for end users to install certificates into Trusted Root

Private material stays under the project's gitignored `.signet/` directory.
"#,
        name = meta.name,
        cn = meta.common_name,
        org = if meta.organization.is_empty() {
            "—"
        } else {
            meta.organization.as_str()
        },
        fp = fp,
        not_before = meta.not_before,
        not_after = meta.not_after,
        algo = meta.key_algorithm,
        tier_id = tier_id,
        tier_meaning = tier_meaning,
        notes_block = notes_block,
        minisign_block = minisign_block,
        android_block = android_block,
        ios_block = ios_block,
        graduation_block = graduation_block,
        platforms = platforms,
        app = app,
    )
}

fn ios_trust_section(project_root: Option<&Path>, config: &Config) -> String {
    let fw = match project_root {
        Some(root) => crate::project::resolve_framework(root, config),
        None => {
            let t = config.project.framework.trim();
            if t.is_empty() {
                return String::new();
            }
            t.to_string()
        }
    };
    if !fw.eq_ignore_ascii_case("ios") {
        return String::new();
    }
    r#"
## iOS

Free Apple ID **development** provisioning typically expires in about **7 days**.  
Packaging an IPA (`signet ios package`) does **not** provide App Store, TestFlight, or notarization trust.

See [docs/ios.md](docs/ios.md). Never tell end users to install developer certificates into a system trust store.
"#
    .to_string()
}

fn graduation_trust_section(config: &Config) -> String {
    let Some(declared) = config.trust.declared_tier.as_deref() else {
        return String::new();
    };
    let lower = declared.to_ascii_lowercase();
    if lower != "ca_authenticode" && lower != "apple_notarized" {
        return String::new();
    }
    r#"
## Graduation

This project declares a reputation-oriented tier (`ca_authenticode` / `apple_notarized`).  
That is maintainer intent for paid CA / Apple notarization paths — it does **not** guarantee SmartScreen or Gatekeeper silence.

Helpers: `signet graduate notes` · [docs/graduation.md](docs/graduation.md).  
Never install publisher certificates into Trusted Root on end-user machines.
"#
    .to_string()
}

fn android_trust_section(secrets_dir: Option<&Path>) -> String {
    let Some(secrets) = secrets_dir else {
        return String::new();
    };
    use crate::android::{keystore_paths, load_meta};
    let paths = keystore_paths(secrets);
    if !paths.exists() {
        return String::new();
    }
    let meta = match load_meta(&paths) {
        Ok(m) => m,
        Err(_) => return String::new(),
    };
    let digest = meta
        .cert_sha256
        .unwrap_or_else(|| "(run `signet android keystore show`)".into());
    format!(
        r#"
## Android (sideload / upload key)

| Field | Value |
|-------|-------|
| Keystore alias | `{alias}` |
| Certificate SHA-256 | `{digest}` |

This digest identifies the **local** signing cert used for sideload / F-Droid-style builds
(or a Play **upload** key). It is **not** Google Play App Signing’s app signing key.

See [docs/android.md](docs/android.md). Never install this certificate into a system trust store.
"#,
        alias = meta.alias,
        digest = digest,
    )
}

fn minisign_trust_section(pub_key: Option<&str>) -> String {
    let Some(pub_key) = pub_key.map(str::trim).filter(|s| !s.is_empty()) else {
        return String::new();
    };
    format!(
        r#"
## Checksum signing (minisign)

Releases may include `SHA256SUMS` attested with this public key (`SHA256SUMS.minisig`).

```
{pub_key}
```

Verify with:

```bash
signet verify --require-sig
# or: minisign -Vm SHA256SUMS -p minisign.pub
```
"#
    )
}

/// Normalize a SHA-256 fingerprint for comparison (strip colons/spaces, lowercase).
pub fn normalize_fingerprint(fp: &str) -> String {
    fp.chars()
        .filter(|c| c.is_ascii_hexdigit())
        .map(|c| c.to_ascii_lowercase())
        .collect()
}

/// Extract SHA-256 fingerprint from a TRUST.md body (Signet table format).
pub fn parse_fingerprint(trust_md: &str) -> Option<String> {
    for line in trust_md.lines() {
        let line = line.trim();
        if !line.contains("fingerprint") && !line.contains("Fingerprint") {
            continue;
        }
        // Table: | SHA-256 fingerprint | `AA:BB:...` |
        if let Some(start) = line.find('`') {
            let rest = &line[start + 1..];
            if let Some(end) = rest.find('`') {
                let raw = &rest[..end];
                let norm = normalize_fingerprint(raw);
                if norm.len() == 64 {
                    return Some(raw.to_string());
                }
            }
        }
    }
    None
}

/// Extract primary tier id from TRUST.md when present.
pub fn parse_tier_id(trust_md: &str) -> Option<String> {
    for line in trust_md.lines() {
        let line = line.trim();
        if !line.contains("Primary tier") {
            continue;
        }
        if let Some(start) = line.find('`') {
            let rest = &line[start + 1..];
            if let Some(end) = rest.find('`') {
                let id = rest[..end].trim();
                if !id.is_empty() {
                    return Some(id.to_string());
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, Trust};
    use crate::identity::{create_identity, CreateOptions};
    use tempfile::tempdir;

    fn sample_identity(dir: &Path) -> IdentityRecord {
        create_identity(
            dir,
            &CreateOptions {
                name: "default".into(),
                common_name: "Trust Demo".into(),
                organization: "Org".into(),
                days: 30,
                force: false,
            },
        )
        .unwrap()
    }

    #[test]
    fn trust_contains_fingerprint_not_key() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains(&rec.meta.fingerprint_sha256));
        assert!(!md.contains(&rec.key_pem));
        assert!(!md.contains("BEGIN PRIVATE KEY"));
        assert!(md.contains("SmartScreen"));
        assert!(md.contains("Gatekeeper"));
    }

    #[test]
    fn trust_contains_tier_and_root_anti_pattern() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains("self_signed_host"));
        assert!(md.contains("## Trust tier"));
        assert!(md.contains("Trusted Root"));
        assert!(md.contains("does not imply"));
        assert!(md.contains("signet verify"));
    }

    #[test]
    fn declared_tier_and_notes_appear() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let mut cfg = Config::example("trust-demo", ".");
        cfg.trust = Trust {
            declared_tier: Some("checksum_only".into()),
            notes: vec!["Beta channel only".into()],
            ..Default::default()
        };
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains("checksum_only"));
        assert!(md.contains("Beta channel only"));
        assert!(md.contains("### Maintainer notes"));
    }

    #[test]
    fn graduation_section_for_ca_tier() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let mut cfg = Config::example("trust-demo", ".");
        cfg.trust.declared_tier = Some("ca_authenticode".into());
        let md = render_trust_md(&cfg, &rec);
        assert!(md.contains("## Graduation"));
        assert!(md.contains("docs/graduation.md"));
    }

    #[test]
    fn parse_fingerprint_from_rendered_trust() {
        let dir = tempdir().unwrap();
        let root = dir.path().join("identity");
        let rec = sample_identity(&root);
        let cfg = Config::example("trust-demo", ".");
        let md = render_trust_md(&cfg, &rec);
        let parsed = parse_fingerprint(&md).expect("fingerprint");
        assert_eq!(
            normalize_fingerprint(&parsed),
            normalize_fingerprint(&rec.meta.fingerprint_sha256)
        );
        assert_eq!(parse_tier_id(&md).as_deref(), Some("self_signed_host"));
    }
}
