//! Emit GitHub Actions workflow for multi-OS Signet ship.

use crate::config::Config;
use crate::ship::coverage::mobile_commitment;
use crate::ship::ci_readiness::required_ci_secrets;
use crate::ship::{assess_sign_profile, ShipSignPath};

const WORKFLOW_PATH: &str = ".github/workflows/signet-ship.yml";

pub fn workflow_rel_path() -> &'static str {
    WORKFLOW_PATH
}

/// Build `signet-ship.yml` body for the platforms declared in config.
pub fn render_signet_ship_workflow(config: &Config) -> String {
    let mut includes = Vec::new();
    if config.platforms.windows {
        includes.push("          - os: windows-latest");
    }
    if config.platforms.macos {
        includes.push("          - os: macos-latest");
    }
    if config.platforms.linux {
        includes.push("          - os: ubuntu-latest");
    }
    if includes.is_empty() {
        includes.push("          - os: ubuntu-latest");
    }
    let matrix = includes.join("\n");
    let (android, ios) = mobile_commitment(config);
    let graduate = assess_sign_profile(config).path == ShipSignPath::Graduate;
    let required = required_ci_secrets(config);

    let mut out = String::new();
    out.push_str(
        "# Generated by `signet ship --ci` — edit for your framework toolchain.\n\
         # Push secrets first: `signet ship secrets --push --apply`\n\
         # After jobs finish: signet ship --collect DIR && signet release --tag vX.Y.Z\n\
         # Partial release: signet release --allow-partial (explicit only).\n\
         # Android keystore ≠ Play; iOS free provisioning ≠ App Store.\n",
    );
    if graduate {
        out.push_str(
            "# Graduate path: restore Azure/OV/Apple credentials (SIGNET_AZURE_*, SIGNET_OV_*, SIGNET_NOTARY_PROFILE).\n",
        );
    }

    out.push_str(
        "\n\
         name: signet-ship\n\
         \n\
         on:\n\
           workflow_dispatch:\n\
           push:\n\
             tags: [\"v*\"]\n\
         \n\
         jobs:\n\
           ship-preflight:\n\
             runs-on: ubuntu-latest\n\
             steps:\n\
               - name: Check Signet CI secrets\n\
                 env:\n",
    );
    for name in &required {
        out.push_str(&format!(
            "                   {name}: ${{{{ secrets.{name} }}}}\n"
        ));
    }
    out.push_str(
        "                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   fail=0\n\
                   require() {\n\
                     local n=\"$1\"\n\
                     if [[ -z \"${!n:-}\" ]]; then\n\
                       echo \"::error::missing repo secret $n — run: signet ship secrets --push --apply\"\n\
                       fail=1\n\
                     fi\n\
                   }\n",
    );
    for name in &required {
        out.push_str(&format!("                   require {name}\n"));
    }
    out.push_str(
        "                   if [[ \"$fail\" -ne 0 ]]; then exit 1; fi\n\
                   echo \"CI secrets preflight ok\"\n\
         \n\
           ship:\n\
             needs: ship-preflight\n\
             strategy:\n\
               fail-fast: false\n\
               matrix:\n\
                 include:\n",
    );
    out.push_str(&matrix);
    out.push('\n');
    out.push_str(
        "             runs-on: ${{ matrix.os }}\n\
         \n\
             steps:\n\
               - uses: actions/checkout@v4\n\
         \n\
               - name: Restore Signet identity (optional)\n\
                 shell: bash\n\
                 env:\n\
                   SIGNET_IDENTITY_BUNDLE_BASE64: ${{ secrets.SIGNET_IDENTITY_BUNDLE_BASE64 }}\n\
                   SIGNET_SUMS_KEY_BASE64: ${{ secrets.SIGNET_SUMS_KEY_BASE64 }}\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -n \"${SIGNET_IDENTITY_BUNDLE_BASE64:-}\" ]]; then\n\
                     mkdir -p .signet\n\
                     echo \"$SIGNET_IDENTITY_BUNDLE_BASE64\" | base64 -d > /tmp/signet-identity.zip\n\
                     unzip -o /tmp/signet-identity.zip -d .signet\n\
                   fi\n\
                   if [[ -n \"${SIGNET_SUMS_KEY_BASE64:-}\" ]]; then\n\
                     mkdir -p .signet/sums\n\
                     echo \"$SIGNET_SUMS_KEY_BASE64\" | base64 -d > .signet/sums/minisign.key\n\
                   fi\n\
         \n\
               - name: Install Rust\n\
                 uses: dtolnay/rust-toolchain@stable\n\
         \n\
               - name: Install Signet\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   cargo install --git https://github.com/Dendro-X0/Signet.git --locked signet\n\
                   signet --version\n\
         \n\
               # Add Node/pnpm/Xcode/etc. steps here for your app framework.\n\
         \n\
               - name: Signet build (host slice)\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -d .signet/identity ]]; then\n\
                     signet build --require-sums-sign\n\
                   else\n\
                     echo \"warning: no .signet/identity — using --no-sign (checksums only)\"\n\
                     signet build --no-sign\n\
                   fi\n",
    );
    if graduate {
        out.push_str(
            "\n\
               - name: Graduate apply (official Sign)\n\
                 if: runner.os == 'Windows' || runner.os == 'macOS'\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   signet graduate apply\n",
        );
    }
    out.push_str(
        "\n\
               - name: Upload ship artifacts\n\
                 uses: actions/upload-artifact@v4\n\
                 with:\n\
                   name: signet-${{ runner.os }}\n\
                   path: |\n\
                     **/SHA256SUMS\n\
                     **/SHA256SUMS.minisig\n\
                     **/bundle/**/*.exe\n\
                     **/bundle/**/*.msi\n\
                     **/bundle/**/*.dmg\n\
                     **/bundle/**/*.AppImage\n\
                     **/bundle/**/*.deb\n\
                     **/bundle/**/*.rpm\n\
                     **/*.apk\n\
                     **/*.aab\n\
                     **/*.ipa\n\
                     dist/**\n\
                   if-no-files-found: warn\n",
    );

    if android {
        out.push_str(
            "\n\
           ship-android:\n\
             needs: ship-preflight\n\
             runs-on: ubuntu-latest\n\
             steps:\n\
               - uses: actions/checkout@v4\n\
         \n\
               - name: Restore Android keystore\n\
                 shell: bash\n\
                 env:\n\
                   SIGNET_ANDROID_KEYSTORE_BASE64: ${{ secrets.SIGNET_ANDROID_KEYSTORE_BASE64 }}\n\
                   SIGNET_ANDROID_META_BASE64: ${{ secrets.SIGNET_ANDROID_META_BASE64 }}\n\
                   SIGNET_ANDROID_STORE_PASS: ${{ secrets.SIGNET_ANDROID_STORE_PASS }}\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -z \"${SIGNET_ANDROID_KEYSTORE_BASE64:-}\" || -z \"${SIGNET_ANDROID_STORE_PASS:-}\" ]]; then\n\
                     echo \"::error::set repo secrets SIGNET_ANDROID_KEYSTORE_BASE64 and SIGNET_ANDROID_STORE_PASS — run: signet ship secrets --push --apply\"\n\
                     exit 1\n\
                   fi\n\
                   mkdir -p .signet/android\n\
                   echo \"$SIGNET_ANDROID_KEYSTORE_BASE64\" | base64 -d > .signet/android/release.jks\n\
                   if [[ -n \"${SIGNET_ANDROID_META_BASE64:-}\" ]]; then\n\
                     echo \"$SIGNET_ANDROID_META_BASE64\" | base64 -d > .signet/android/meta.toml\n\
                   fi\n\
         \n\
               - name: Install Rust\n\
                 uses: dtolnay/rust-toolchain@stable\n\
         \n\
               - name: Install Signet\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   cargo install --git https://github.com/Dendro-X0/Signet.git --locked signet\n\
                   signet --version\n\
         \n\
               # Add JDK / Android SDK / Gradle / Expo steps for your mobile target.\n\
         \n\
               - name: Signet build (Android slice)\n\
                 shell: bash\n\
                 env:\n\
                   SIGNET_ANDROID_STORE_PASS: ${{ secrets.SIGNET_ANDROID_STORE_PASS }}\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -d .signet/identity ]]; then\n\
                     signet build --require-sums-sign\n\
                   else\n\
                     echo \"warning: no .signet/identity — using --no-sign (checksums only)\"\n\
                     signet build --no-sign\n\
                   fi\n\
         \n\
               - name: Upload Android artifacts\n\
                 uses: actions/upload-artifact@v4\n\
                 with:\n\
                   name: signet-android\n\
                   path: |\n\
                     **/SHA256SUMS\n\
                     **/SHA256SUMS.minisig\n\
                     **/*.apk\n\
                     **/*.aab\n\
                     dist/**\n\
                   if-no-files-found: warn\n",
        );
    }

    if ios {
        out.push_str(
            "\n\
           ship-ios:\n\
             needs: ship-preflight\n\
             runs-on: macos-latest\n\
             steps:\n\
               - uses: actions/checkout@v4\n\
         \n\
               - name: Install Rust\n\
                 uses: dtolnay/rust-toolchain@stable\n\
         \n\
               - name: Install Signet\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   cargo install --git https://github.com/Dendro-X0/Signet.git --locked signet\n\
                   signet --version\n\
         \n\
               # Apple development team / provisioning must be configured on the runner.\n\
               # Signet does not provide App Store trust. See docs/ios.md.\n\
         \n\
               - name: Signet build (iOS slice)\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -d .signet/identity ]]; then\n\
                     signet build --require-sums-sign\n\
                   else\n\
                     echo \"warning: no .signet/identity — using --no-sign (checksums only)\"\n\
                     signet build --no-sign\n\
                   fi\n\
         \n\
               - name: Upload iOS artifacts\n\
                 uses: actions/upload-artifact@v4\n\
                 with:\n\
                   name: signet-ios\n\
                   path: |\n\
                     **/SHA256SUMS\n\
                     **/SHA256SUMS.minisig\n\
                     **/*.ipa\n\
                     dist/**\n\
                   if-no-files-found: warn\n",
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, Target};

    #[test]
    fn matrix_follows_declared_platforms() {
        let mut cfg = Config::example("app", ".");
        cfg.platforms.windows = true;
        cfg.platforms.macos = true;
        cfg.platforms.linux = false;
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("windows-latest"), "{yml}");
        assert!(yml.contains("macos-latest"), "{yml}");
        assert!(yml.contains("ship-preflight"), "{yml}");
        assert!(yml.contains("needs: ship-preflight"), "{yml}");
        assert!(yml.contains("signet build"));
        assert!(!yml.contains("ship-android"));
        // preflight runs on ubuntu even when linux desktop is undeclared
        assert!(yml.contains("ubuntu-latest"), "{yml}");
        assert!(!yml.contains("graduate apply"), "{yml}");
    }

    #[test]
    fn android_job_when_expo_target() {
        let mut cfg = Config::example("app", ".");
        cfg.platforms.windows = true;
        cfg.platforms.macos = false;
        cfg.platforms.linux = false;
        cfg.targets.push(Target {
            id: "mobile".into(),
            framework: "expo".into(),
            app_root: "apps/mobile".into(),
            build_command: String::new(),
        });
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("ship-android"), "{yml}");
        assert!(yml.contains("ship-ios"), "{yml}");
        assert!(yml.contains("Restore Android keystore"), "{yml}");
        assert!(yml.contains("signet ship secrets --push --apply"), "{yml}");
        assert!(yml.contains("**/*.apk"));
    }

    #[test]
    fn android_job_when_platforms_android() {
        let mut cfg = Config::example("app", ".");
        cfg.platforms.android = true;
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("ship-android"), "{yml}");
        assert!(!yml.contains("ship-ios"), "{yml}");
        assert!(yml.contains("SIGNET_ANDROID_KEYSTORE_BASE64"), "{yml}");
    }

    #[test]
    fn graduate_apply_step_when_path_graduate() {
        let mut cfg = Config::example("app", ".");
        cfg.ship.path = "graduate".into();
        cfg.graduation.azure.dlib = "dlib.dll".into();
        cfg.graduation.azure.metadata = "meta.json".into();
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("signet graduate apply"), "{yml}");
        assert!(yml.contains("Graduate apply"), "{yml}");
        assert!(yml.contains("SIGNET_AZURE_"), "{yml}");
    }

    #[test]
    fn preflight_lists_identity_secret() {
        let cfg = Config::example("app", ".");
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("SIGNET_IDENTITY_BUNDLE_BASE64"), "{yml}");
        assert!(yml.contains("::error::missing repo secret"), "{yml}");
    }
}
