//! Emit GitHub Actions workflow for multi-OS Signet ship.

use crate::config::Config;

const WORKFLOW_PATH: &str = ".github/workflows/signet-ship.yml";

pub fn workflow_rel_path() -> &'static str {
    WORKFLOW_PATH
}

/// Build `signet-ship.yml` body for the platforms declared in config.
pub fn render_signet_ship_workflow(config: &Config) -> String {
    let mut includes = Vec::new();
    if config.platforms.windows {
        includes.push("          - os: windows-latest");
    }
    if config.platforms.macos {
        includes.push("          - os: macos-latest");
    }
    if config.platforms.linux {
        includes.push("          - os: ubuntu-latest");
    }
    if includes.is_empty() {
        includes.push("          - os: ubuntu-latest");
    }
    let matrix = includes.join("\n");

    let mut out = String::new();
    out.push_str(
        "# Generated by `signet ship --ci` — edit for your framework toolchain.\n\
         # After the matrix finishes, download job artifacts and run:\n\
         #   signet ship --collect ./downloaded-artifacts\n\
         #   signet release --tag vX.Y.Z\n\
         # Do not commit signing secrets; restore `.signet/identity` via Actions secrets.\n\
         \n\
         name: signet-ship\n\
         \n\
         on:\n\
           workflow_dispatch:\n\
           push:\n\
             tags: [\"v*\"]\n\
         \n\
         jobs:\n\
           ship:\n\
             strategy:\n\
               fail-fast: false\n\
               matrix:\n\
                 include:\n",
    );
    out.push_str(&matrix);
    out.push('\n');
    out.push_str(
        "             runs-on: ${{ matrix.os }}\n\
         \n\
             steps:\n\
               - uses: actions/checkout@v4\n\
         \n\
               - name: Install Rust\n\
                 uses: dtolnay/rust-toolchain@stable\n\
         \n\
               - name: Install Signet\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   cargo install --git https://github.com/Dendro-X0/Signet.git --locked signet\n\
                   signet --version\n\
         \n\
               # Add Node/pnpm/Xcode/etc. steps here for your app framework.\n\
         \n\
               - name: Signet build (host slice)\n\
                 shell: bash\n\
                 run: |\n\
                   set -euo pipefail\n\
                   if [[ -d .signet/identity ]]; then\n\
                     signet build --require-sums-sign\n\
                   else\n\
                     echo \"warning: no .signet/identity — using --no-sign (checksums only)\"\n\
                     signet build --no-sign\n\
                   fi\n\
         \n\
               - name: Upload ship artifacts\n\
                 uses: actions/upload-artifact@v4\n\
                 with:\n\
                   name: signet-${{ runner.os }}\n\
                   path: |\n\
                     **/SHA256SUMS\n\
                     **/SHA256SUMS.minisig\n\
                     **/bundle/**/*.exe\n\
                     **/bundle/**/*.msi\n\
                     **/bundle/**/*.dmg\n\
                     **/bundle/**/*.AppImage\n\
                     **/bundle/**/*.deb\n\
                     **/bundle/**/*.rpm\n\
                     dist/**\n\
                   if-no-files-found: warn\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    #[test]
    fn matrix_follows_declared_platforms() {
        let mut cfg = Config::example("app", ".");
        cfg.platforms.windows = true;
        cfg.platforms.macos = true;
        cfg.platforms.linux = false;
        let yml = render_signet_ship_workflow(&cfg);
        assert!(yml.contains("windows-latest"), "{yml}");
        assert!(yml.contains("macos-latest"), "{yml}");
        assert!(!yml.contains("ubuntu-latest"), "{yml}");
        assert!(yml.contains("signet build"));
        assert!(yml.contains("${{ matrix.os }}"));
    }
}
