use crate::config::Config;
use crate::identity::IdentityRecord;

pub fn build_release_notes(
    config: &Config,
    tag: &str,
    identity: Option<&IdentityRecord>,
    trust_attached: bool,
) -> String {
    let mut body = String::new();
    body.push_str(&format!("## {} {}\n\n", config.project.name, tag));
    body.push_str("Self-signed release published with `signet release`.\n\n");
    body.push_str(
        "OS warnings (SmartScreen / Gatekeeper) may still appear — that is expected for \
         self-signed / low-reputation certificates. Prefer fingerprint + SHA256SUMS checks \
         over the absence of a warning.\n\n",
    );

    if let Some(id) = identity {
        body.push_str("### Publisher fingerprint\n\n");
        body.push_str(&format!("- Identity: `{}`\n", id.meta.name));
        body.push_str(&format!("- CN: `{}`\n", id.meta.common_name));
        body.push_str(&format!(
            "- SHA-256: `{}`\n\n",
            id.meta.fingerprint_sha256
        ));
    }

    body.push_str("### Verify\n\n");
    body.push_str("1. Download `SHA256SUMS` and the installer for your platform.\n");
    body.push_str("2. Verify checksums (`sha256sum -c SHA256SUMS` or equivalent).\n");
    if trust_attached {
        body.push_str("3. Read `TRUST.md` for platform-specific trust notes.\n");
    } else {
        body.push_str("3. Compare the signing certificate fingerprint with the project docs.\n");
    }
    body.push('\n');
    body.push_str("---\n");
    body.push_str("*Generated by [Signet](https://github.com/Dendro-X0/Signet).*\n");
    body
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    #[test]
    fn notes_mention_self_signed() {
        let cfg = Config::example("demo", ".");
        let notes = build_release_notes(&cfg, "v1.0.0", None, true);
        assert!(notes.contains("Self-signed"));
        assert!(notes.contains("SHA256SUMS"));
        assert!(notes.contains("TRUST.md"));
    }
}
